### ISSUE TITLE
Compiler error gcc 10.1.0

### ISSUE THREAD

**Issue by jacobmerson** [SCOREC/core#334]
Default build using gcc 10.1.0

```
In file included from /usr/include/string.h:633,
                 from /lore/mersoj/boundary-conditions-deps/core/phasta/phIO.c:2:
/lore/mersoj/boundary-conditions-deps/core/phasta/phIO.c: In function 'find_header':
/lore/mersoj/boundary-conditions-deps/core/phasta/phIO.c:84:7: error: '__builtin_strncpy' specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
   84 |       strncpy(found, hname, strlen(hname));
      |       ^~~~~~~
/lore/mersoj/boundary-conditions-deps/core/phasta/phIO.c:84:7: note: length computed here
```

**Comment by cwsmith** [comment]
I'm not sure why, but some of the phasta pre-processor (`chef`) tests failed.  I reverted the commit (https://github.com/SCOREC/core/commit/897ffdad5afb65194d769ef3d290a31eb6987a70) until we can test/investigate this some more.

**Comment by cwsmith** [comment]
This is fixed again with https://github.com/SCOREC/core/commit/06119fc71d6599fbab531c24b20370b08aa1465a.  I didn't see any chef errors running on SCOREC Rhel7 and my arch linux desktop.

**Comment by cwsmith** [comment]
Spoke too soon.  The errors appear in tests using Simmetrix: https://my.cdash.org/test/34314082

**Comment by cwsmith** [comment]
`chef7` 
-  is a diff of the output from `chef6` against 'good' output
- `chef6` runs without any obvious issues
- Given the change, it is likely a string in the gcc10 build's output that changed.


`ph_adapt`
- loads a simmetrix geomsim smd model and scorec smb mesh 
- reads from `1-procs_case` directory of the test directory
- In the gcc 10 build the fields attach correctly, and there is a failure while accessing/checking the `motion_coords` field.  The full output is below.  This appears to be a completely different error mode than seen in the nightly build+test using gcc 7.

```
Start testing: Jun 11 16:06 EDT                                                                                                                                                                                                                                                 
----------------------------------------------------------                                                                                                                                                                                                                      
31/138 Testing: ph_adapt                                                                                                                                                                                                                                                        
31/138 Test: ph_adapt                                                                                                                                                                                                                                                           
Command: "/opt/scorec/spack/v0154_2/install/linux-rhel7-x86_64/gcc-10.1.0/mpich-3.3.2-gi3wrjquyo564rk27x6r2c6ilr7ndmpl/bin/mpirun" "-np" "1" "/space/cwsmith/build-core-gcc10-rhel7/test/ph_adapt" "/lore/cwsmith/geometries/pumi-meshes//phasta/loopDriver/model.smd" "/lore/cwsmith/geometries/pumi-meshes//phasta/loopDriver/mesh_.smb"                                                                                                                                                                                                                      
Directory: /lore/cwsmith/geometries/pumi-meshes//phasta/loopDriver                                                                                                                                                                                                              
"ph_adapt" start time: Jun 11 16:06 EDT                                                                                                                                                                                                                                         
Output:                                                                                                                                                                                                                                                                         
----------------------------------------------------------                                                                                                                                                                                                                      
model /lore/cwsmith/geometries/pumi-meshes//phasta/loopDriver/model.smd loaded in 0.001145 seconds                                                                                                                                                                              
mesh /lore/cwsmith/geometries/pumi-meshes//phasta/loopDriver/mesh_.smb loaded in 0.933791 seconds                                                                                                                                                                               
number of tet 221345 hex 0 prism 0 pyramid 0                                                                                                                                                                                                                                    
mesh entity counts: v 37514 e 259396 f 443228 r 221345                                                                                                                                                                                                                          
mesh verified in 2.408857 seconds                                                                                                                                                                                                                                               
unknown restart field name "time der"                                                                                                                                                                                                                                           
please add "time der" to isNodalField above line 324 of /users/cwsmith/develop/core/phasta/phRestart.cc                                                                                                                                                                         
assuming "time der" is a nodal field,                                                                                                                                                                                                                                           
it is the right size...                                                                                                                                                                                                                                                         
unknown restart field name "motion_c"                                                                                                                                                                                                                                           
please add "motion_c" to isNodalField above line 324 of /users/cwsmith/develop/core/phasta/phRestart.cc                                                                                                                                                                         
assuming "motion_c" is a nodal field,                                                                                                                                                                                                                                           
it is the right size...                                                                                                                                                                                                                                                         
fields read and attached in 0.028781 seconds                                                                                                                                                                                                                                    
f failed at /users/cwsmith/develop/core/test/ph_adapt.cc + 24                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                
===================================================================================                                                                                                                                                                                             
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES                                                                                                                                                                                                                        
=   PID 339 RUNNING AT cranium.scorec.rpi.edu                                                                                                                                                                                                                                   
=   EXIT CODE: 134                                                                                                                                                                                                                                                              
=   CLEANING UP REMAINING PROCESSES                                                                                                                                                                                                                                             
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES                                                                                                                                                                                                                                   
===================================================================================                                                                                                                                                                                             
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)                                                                                                                                                                                                            
This typically refers to a problem with your application.                                                                                                                                                                                                                       
Please see the FAQ page for debugging suggestions                                                                                                                                                                                                                               
<end of output>                                                                                                                                                                                                                                                                 
Test time =   3.72 sec                                                                                                                                                                                                                                                          
----------------------------------------------------------                                                                                                                                                                                                                      
Test Failed.                                                                                                                                                                                                                                                                    
"ph_adapt" end time: Jun 11 16:06 EDT                                                                                                                                                                                                                                           
"ph_adapt" time elapsed: 00:00:03                                                                                                                                                                                                                                               
----------------------------------------------------------                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                
End testing: Jun 11 16:06 EDT                                                                                                                                                                                                                                                   
```
```
